### ISSUE TITLE
Hang on "Install KF2 Classic (be patient)" in Proxmox VM

### ISSUE THREAD

**Issue by triuk** [noobient/killinuxfloor#48]
Hi, I've had your KF2 server in the VM since it was "kf2-centos" and after ~2 years I had to reinstall it.
Unfortunately your newest version hangs on installation process. And yes, I am patient, I've let it be for 4 days and it is still like this without any network or disk I/O movement.
It is done on fresh CentOS7, but I've also tried it on CentOS8. Container or VM, still the same result.
Since the installer is not verbose, I do not know, what exactly went wrong.

**Comment by bviktor** [comment]
Indeed. Thanks for reporting. There were probably some changes in Steam's CDN and/or API which caused the old DepotDownloader to get stuck on obtaining KF2. Upgrading DepotDownloader appears to have solved the issue, so I didn't investigate further.

However, please note that due to the increasingly complicated way some dependencies had to be dealt with on EL7, I've dropped support for that (CentOS 7, RHEL 7, etc.).

Due to the mess around EL these days, my main focus is now Fedora Server, and the current git version should be working fine with that. I've tried to keep the code functional on EL8, but that hasn't been tested yet (I'll try to do that eventually, too).

But also note that I'm planning to switch back the KF2 version to the latest, and KF2 Classic will become an option for those who want it. How that'll be done is TBD, I'll prolly sort it out in the coming hours/days. It'lls probably be a flag given to the installer, like `./install --classic` or something.

**Comment by bviktor** [comment]
Closing the issue, please let me know if it still needs fixing.
